# Generated by Django 4.0.4 on 2022-05-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20220409_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
