# Generated by Django 4.0.4 on 2022-05-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_work_district_work_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='users_dist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='users_state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
